# until we register the app, we do not need to set the id
application: terpsichore-music
version: 2
# do we want to get this to python3 or does it not matter?
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts

- url: /css
  static_dir: css

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /style
  static_dir: style

- url: /.*
  script: driver.application

libraries:
- name: webapp2
  version: latest
- name: numpy 
  version: latest
