# until we register the app, we do not need to set the id
application: my-app-id 
version: 1
# do we want to get this to python3 or does it not matter?
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts

- url: /style
  static_dir: style

- url: /.*
  script: driver.application

libraries:
- name: webapp2
  version: latest
- name: numpy 
  version: latest
